# Generated by Django 5.2 on 2025-04-26 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Kursnamn (på basspråket)"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Beskrivning (på basspråket)"
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("sv", "Swedish"),
                            ("es", "Spanish"),
                            ("fr", "French"),
                            ("de", "German"),
                            ("ru", "Russian"),
                            ("lv", "Latvian"),
                            ("et", "Estonian"),
                            ("lt", "Lithuanian"),
                            ("fi", "Finnish"),
                        ],
                        max_length=10,
                        verbose_name="Språk att lära sig",
                    ),
                ),
                (
                    "base_language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("sv", "Swedish"),
                            ("es", "Spanish"),
                            ("fr", "French"),
                            ("de", "German"),
                            ("ru", "Russian"),
                            ("lv", "Latvian"),
                            ("et", "Estonian"),
                            ("lt", "Lithuanian"),
                            ("fi", "Finnish"),
                        ],
                        max_length=10,
                        verbose_name="Basspråk",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="Publik kurs"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_courses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True,
                        related_name="joined_courses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Kurs",
                "verbose_name_plural": "Kurser",
            },
        ),
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(max_length=8000)),
                ("text", models.TextField(max_length=8000)),
                ("order", models.PositiveIntegerField(default=1)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modules",
                        to="core.course",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Sentence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(blank=True, max_length=1000)),
                ("translation", models.TextField(blank=True)),
                (
                    "audio",
                    models.FileField(
                        blank=True, null=True, upload_to="sentence_audio/"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sentences",
                        to="core.module",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(blank=True, max_length=100)),
                ("translation", models.CharField(blank=True, max_length=255)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="word_images/"),
                ),
                (
                    "audio",
                    models.FileField(blank=True, null=True, upload_to="word_audio/"),
                ),
                (
                    "example_sentence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="example_words",
                        to="core.sentence",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="words",
                        to="core.module",
                    ),
                ),
            ],
        ),
    ]
