# Generated by Django 5.2 on 2025-04-25 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Kursnamn (på basspråket)"
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "Engelska"),
                            ("sv", "Svenska"),
                            ("es", "Spanska"),
                            ("fr", "Franska"),
                            ("de", "Tyska"),
                            ("ru", "Ryska"),
                            ("lv", "Lettiska"),
                            ("et", "Estniska"),
                            ("lt", "Litauiska"),
                            ("fi", "Finska"),
                        ],
                        max_length=10,
                        verbose_name="Språk att lära sig",
                    ),
                ),
                (
                    "base_language",
                    models.CharField(
                        choices=[
                            ("en", "Engelska"),
                            ("sv", "Svenska"),
                            ("es", "Spanska"),
                            ("fr", "Franska"),
                            ("de", "Tyska"),
                            ("ru", "Ryska"),
                            ("lv", "Lettiska"),
                            ("et", "Estniska"),
                            ("lt", "Litauiska"),
                            ("fi", "Finska"),
                        ],
                        max_length=10,
                        verbose_name="Basspråk",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="Publik kurs"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_courses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True,
                        related_name="joined_courses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Kurs",
                "verbose_name_plural": "Kurser",
            },
        ),
    ]
