# Generated by Django 5.2 on 2025-04-26 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_course_options_alter_module_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="word",
            options={
                "ordering": ["text"],
                "verbose_name": "Ord",
                "verbose_name_plural": "Ord",
            },
        ),
    ]
