# Generated by Django 5.2 on 2025-04-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_word_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='excluded_words',
            field=models.CharField(
                blank=True,
                help_text='Komma-separerad lista av ord som inte ska skapa Word-objekt.',
                max_length=2000,
            ),
        ),
        migrations.AlterField(
            model_name='module',
            name='description',
            field=models.TextField(max_length=8000),
        ),
        migrations.AlterField(
            model_name='module',
            name='text',
            field=models.TextField(max_length=8000),
        ),
    ]
