# Generated by Django 5.2 on 2025-04-27 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_usermodule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodule',
            name='module',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='usermodules',
                to='core.module',
            ),
        ),
    ]
