# Generated by Django 5.2 on 2025-04-27 15:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_usermodule_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodule',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
