# Generated by Django 5.2 on 2025-04-27 15:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_usermodule_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermodule',
            options={
                'ordering': ['started_at'],
                'verbose_name': 'Användarmodul',
                'verbose_name_plural': 'Användarmoduler',
            },
        ),
        migrations.AddField(
            model_name='usermodule',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usermodule',
            name='started_at',
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
