# Generated by Django 5.2 on 2025-05-06 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_exercise_studentexerciseresponse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='instructions',
            new_name='considerations',
        ),
        migrations.RenameField(
            model_name='exercise',
            old_name='title',
            new_name='name',
        ),
    ]
